[package]
name = "udp_to_kafka_forwarding"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
utilities = {path = "utilities"}
tasks = {path = "tasks"}
mimalloc = { version = "*", default-features = false }

[profile.release]
lto = true
strip = true
panic = "abort"