[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
utilities = {path = "../utilities"}

rand = "0.8.5"
async-trait = "0.1.58"
tokio = { version = "1.21.2", features = ["full"] }
rdkafka = { version = "0.29", features = ["cmake-build","zstd-pkg-config"] }
