[package]
name = "tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
utilities = {path = "../utilities"}

fastrand = "1.8.0"
async-trait = "0.1.58"
rustc-hash = "1.1.0"
ustr = "0.9.0"
tokio = { version = "1.22.0", features = ["full"] }
rdkafka = { version = "0.29", features = ["cmake-build","zstd-pkg-config"] }