[package]
name = "utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
simple_logger = "4.0.0"
envconfig = "0.10.0"
strum = { version = "0.24.1", features = ["derive"]}
byte-unit = "4.0.17"
derive-new = "0.5"
